version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    # Nếu cần, có thể mở port (nếu chạy cục bộ)
    ports:
      - "8080:8080"
      - "8000:8000"
